config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'result/showResult'

  get 'user/login'

  get 'user/signup'

  get 'user/viewProfile'

  get 'user/notLoggedIn'

  get 'home/index'

  get 'user' => "user#refresh"

  get 'error' => 'error#index'

  get 'facility/new'

  post 'facility' => 'facility#create'

  delete 'facility' => 'facility#delete', :as => 'delete_post'

  get 'facility/:facilityId' => 'facility#show'

  get 'result/showResult' => "result#showResult"

  root 'home#index'

  get 'room_page/roomInfo'

  get 'facility/edit'
  post 'facility/editReview' => 'facility#editReview'

end

app/views/layouts/_deviseErrors.erb
<% if object.errors.any? %>
<p><strong>Please correct the following errors:</strong></p>
<ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

app/views/layouts/_post.erb
<%
room = Room.where('id = ?', post.room_id).first
roomNum = room.roomNum
building = (Building.where('id = ?', room.building_id).first)
buildingName = building.name
facility = (FacilityType.where('id = ?', room.facilitytype_id).first)
date = Date.parse(post.created_at.to_s)
if facility != nil then
    type = facility.ftype
else
    type = "Lab"
end
%>

<hr />

<p class="postRating">
    <strong><%= post.rating %>/5</strong>
</p>
<p class='buildingName'>
    <%= buildingName %>
    <%= roomNum %>
    (<%= type %>)
</p>

<br />
<blockquote class="blockquote">
  <p class="mb-0"><%= post.review %></p>
  <footer class="blockquote-footer"><%= user %>, <cite title="Source Title"><%= date %></cite></footer>
</blockquote>

<% if user_signed_in? && current_user.email == User.find(post.user_id).email then %>
    <%=link_to "Edit", "../facility/edit?id="+post.id.to_s+"&review="+post.review+"&rating="+post.rating.to_s+"&building="+buildingName.to_s+"&room="+roomNum.to_s+"&facility="+facility.ftype.to_s, class:'btn btn-default btn-sm' %>
    <%=link_to 'Delete', delete_post_path(:id => post.id),  method: "delete", class:'btn btn-default btn-sm' %>

<% end %>

<br />

app/views/layouts/_searchBar.html.erb
 <% types = FacilityType.all%>
 <% building = Building.all%>
 <% typeShow = types.map { |val| val.ftype } %>
 <% typeShow.sort! %>
 <% buildingShow = building.map { |val| val.name } %>
    <div class="row top-filter form-inline">
     <%= form_tag("/result/showResult", method: "get") do %>
            <div class="form-group">
            <label>Building
             <%= select_tag(:building, options_for_select(buildingShow), prompt: "Select a Building", class:"buildingInput") %>
            </label>
            <label>Facility
               <%= select_tag(:facility, options_for_select(typeShow), prompt: "Select a Facility") %>
            </label>
            <label>Room
             <%= text_field_tag(:room, @tempRoom) %>
            </label>
            </div>
            <%= submit_tag("Search", class: "btn btn-primary inresult") %>
        <%end%>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facilirate</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAVtPCepecolaHrw-pp9SPRmqk64LTynX0&callback=initMap"
  type="text/javascript"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>